const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();
const home=document.querySelector('#home'),screen=document.querySelector('#screen'),badge=document.querySelector('#profileBadge'),toast=document.querySelector('#toast');const user=tg?.initDataUnsafe?.user;if(user)badge.textContent=user.first_name||user.username||'Профиль';
const items=[['💼','Агенты','Заявка и кабинет агента','agents'],['🤝','Партнёры','Регистрация и партнёрские условия','partners'],['🖼️','Получить баннер','Рекламные материалы','banners'],['🔎','Проверить контакт','Проверка @username или email','check'],['🛡️','Заблокированный контакт','Проверка по блок-листу','blocked'],['❔','Вопросы и ответы','Ответы для агентов и партнёров','faq'],['💬','Поддержка','Связаться с командой','support'],['👤','Личный кабинет','Ваш профиль и статус','profile']];
function haptic(){tg?.HapticFeedback?.impactOccurred('light')}function notify(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
function showHome(){haptic();tg?.BackButton?.hide();screen.hidden=true;home.hidden=false;home.innerHTML=`<section class="hero"><span class="hero-orb">✦</span><p class="eyebrow">Partners Portal</p><h1>Ваша партнёрская программа в одном месте</h1><p>Заявки, материалы, поддержка и личный кабинет — удобно внутри Telegram.</p></section><p class="section-title">Выберите раздел</p><div class="menu">${items.map(([i,t,d,k])=>`<button class="menu-card" onclick="openScreen('${k}')"><span class="menu-icon">${i}</span><span><strong>${t}</strong><small>${d}</small></span><span class="arrow">›</span></button>`).join('')}</div>`}
function header(title){return `<div class="topline"><button class="back" onclick="showHome()">‹ Назад</button><h2 class="screen-title">${title}</h2></div>`}
function form(kind){const agent=kind==='agents';const title=agent?'Стать агентом':'Стать партнёром';return `${header(title)}<p class="lead">Заполните заявку — команда рассмотрит её и свяжется с вами в Telegram.</p><form onsubmit="submitApplication(event,'${kind}')"><div class="field"><label>Ваше имя</label><input required name="name" value="${user?.first_name||''}" placeholder="Имя"></div><div class="field"><label>${agent?'Страна и город':'GEO'}</label><input required name="geo" placeholder="Например: Казахстан, Алматы"></div><div class="field"><label>Email</label><input required type="email" name="email" placeholder="name@example.com"></div>${agent?`<div class="field"><label>Номер телефона</label><input name="phone" placeholder="+7 000 000 00 00"></div><div class="field"><label>Опыт работы</label><textarea name="experience" placeholder="Коротко расскажите об опыте"></textarea></div>`:`<div class="field"><label>Источник трафика</label><input name="traffic" placeholder="Telegram, сайт, Instagram и т.д."></div><div class="field"><label>Сайт / канал / соцсеть</label><input name="source" placeholder="Ссылка или @username"></div>`}<div class="field"><label>Комментарий</label><textarea name="comment" placeholder="Дополнительная информация"></textarea></div><label class="checkline"><input type="checkbox" required> Согласен с условиями обработки заявки</label><button class="btn primary" type="submit">Отправить заявку</button></form><div class="card"><h3>${agent?'Я уже агент':'Я уже партнёр'}</h3><p>После одобрения данные профиля появятся в личном кабинете.</p></div>`}
function checkScreen(blocked=false){const title=blocked?'Заблокированный контакт':'Проверить контакт';return `${header(title)}<p class="lead">${blocked?'Проверьте Telegram, email, Agent ID или Affiliate ID.':'Укажите @username или email.'}</p><div class="field"><label>Контакт</label><input id="lookup" placeholder="@username или email"></div><button class="btn primary" onclick="runCheck(${blocked})">Проверить</button><div id="checkResult"></div>`}
function faq(){const q=['Какие виды трафика разрешены?','Какие модели сотрудничества доступны?','Как рассчитывается комиссия?','Как часто обновляется статистика?','Когда происходят выплаты?','Как связаться с менеджером?'];return `${header('Вопросы и ответы')}<div class="tabs"><button class="tab active" onclick="switchFaq(this,'partner')">Для партнёров</button><button class="tab" onclick="switchFaq(this,'agent')">Для агентов</button></div><div class="faq">${q.map((x,i)=>`<details ${i===0?'open':''}><summary>${x}</summary><p>Ответ будет доступен после публикации правил программы. Для точной информации создайте обращение в поддержку.</p></details>`).join('')}</div>`}
function banners(){return `${header('Получить баннер')}<p class="lead">Первые материалы доступны как placeholders. После загрузки администратором здесь появятся ваши баннеры.</p><div class="card"><div class="banner-preview">PARTNERS<br>YOUR CAMPAIGN</div><h3>Баннер 1200 × 628</h3><p><span class="pill">Telegram</span> <span class="pill">Общий GEO</span></p><div class="actions"><button class="btn" onclick="notify('Материал будет доступен после загрузки')">Открыть preview</button><button class="btn primary" onclick="notify('Рекламный текст скопирован')">Скопировать рекламный текст</button></div></div>`}
function support(){return `${header('Поддержка')}<p class="lead">Мы поможем с заявкой, доступами и рекламными материалами.</p><div class="actions"><button class="btn primary" onclick="notify('Откроем чат с менеджером после настройки поддержки')">💬 Написать менеджеру</button><button class="btn" onclick="openTicket()">✉️ Создать обращение</button><button class="btn" onclick="openScreen('faq')">❔ Открыть FAQ</button></div>`}
function profile(){return `${header('Личный кабинет')}<div class="card"><h3>${user?.first_name||'Пользователь Telegram'}</h3><p>${user?.username?'@'+user.username:'Username не указан'}<br>Telegram ID: ${user?.id||'будет определён при открытии в Telegram'}<br>Роль: гость<br>Статус: ожидает регистрации</p></div><button class="btn primary" onclick="openScreen('agents')">Подать заявку агента</button><button class="btn" onclick="openScreen('partners')">Подать заявку партнёра</button>`}
function openTicket(){screen.innerHTML=`${header('Новое обращение')}<form onsubmit="submitTicket(event)"><div class="field"><label>Тема</label><input required placeholder="Например: вопрос по регистрации"></div><div class="field"><label>Категория</label><select><option>Общий вопрос</option><option>Заявка</option><option>Материалы</option><option>Техническая проблема</option></select></div><div class="field"><label>Сообщение</label><textarea required placeholder="Опишите вопрос"></textarea></div><button class="btn primary">Отправить обращение</button></form>`}
function openScreen(k){haptic();home.hidden=true;screen.hidden=false;const map={agents:()=>form('agents'),partners:()=>form('partners'),banners,check:()=>checkScreen(false),blocked:()=>checkScreen(true),faq,support,profile};screen.innerHTML=map[k]();tg?.BackButton?.show();tg?.BackButton?.onClick(showHome)}
function submitApplication(e,kind){e.preventDefault();e.target.querySelector('button').disabled=true;notify(`Заявка ${kind==='agents'?'агента':'партнёра'} отправлена`);setTimeout(showHome,900)}function submitTicket(e){e.preventDefault();notify('Обращение создано');setTimeout(showHome,900)}function runCheck(blocked){const value=document.querySelector('#lookup').value.trim(),out=document.querySelector('#checkResult');if(!value){notify('Введите контакт для проверки');return}out.innerHTML=`<div class="result ${blocked?'warn':''}">${blocked?'✅ Контакт не находится в блок-листе':'✅ Контакт свободен'}</div>`}function switchFaq(el,type){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));el.classList.add('active');notify(type==='agent'?'Показаны вопросы для агентов':'Показаны вопросы для партнёров')}showHome();
