import { esc, icon, pageHead } from './ui.js?v=20260826-3';
import { t } from './screens.js?v=20260901-01';

const e = value => esc(value ?? '');
const button = (label, attrs = '', kind = 'primary') => `<button class="app-btn ${kind}" ${attrs}>${label}</button>`;
const tr = (lang, key, values) => t(lang, `giveaway.${key}`, values);
const localeDate = (value, lang) => value ? new Date(value).toLocaleString(lang === 'ru' ? 'ru-RU' : lang === 'tg' ? 'tg-TJ' : lang === 'uz' ? 'uz-UZ' : lang === 'tr' ? 'tr-TR' : 'en-GB', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const geoName = (code, settings = []) => settings.find(item => item.geo_code === code)?.country || code;
const giveawayTitle = (giveaway, lang) => giveaway?.title?.trim() || tr(lang, 'title');
const statusLabel = (status, lang) => ({ active: tr(lang, 'active'), closed: tr(lang, 'closed'), drawn: tr(lang, 'drawn'), cancelled: tr(lang, 'cancelAction'), draft: '📝 Draft', excluded: tr(lang, 'excluded'), winner: `🏆 ${tr(lang, 'winners')}` }[status] || status);

function giveawayHero(giveaway, settings = [], lang = 'ru') {
  return `<section class="giveaway-hero">
    ${giveaway.banner_url ? `<img src="${e(giveaway.banner_url)}" alt="${e(tr(lang, 'banner'))}">` : `<div class="giveaway-hero-art">${icon('gift')}<span>PARTNERS<br>GIVEAWAY</span></div>`}
    <div class="giveaway-hero-copy"><span>${tr(lang, 'current')}</span><h1>${e(giveawayTitle(giveaway, lang))}</h1>${giveaway.description?.trim() ? `<p>${e(giveaway.description)}</p>` : ''}</div>
    <div class="giveaway-prize"><span>${tr(lang, 'prize')}</span><b>${e(giveaway.prize)}</b></div>
    <div class="giveaway-facts"><article><span>${icon('trophy')} ${tr(lang, 'winners')}</span><b>${giveaway.winner_count}</b></article><article><span>▶️ ${tr(lang, 'start')}</span><b>${localeDate(giveaway.start_at, lang)}</b></article><article><span>⏹ ${tr(lang, 'end')}</span><b>${localeDate(giveaway.end_at, lang)}</b></article></div>
    <div class="giveaway-geos">${giveaway.geo_codes.map(code => `<span>${e(geoName(code, settings))}</span>`).join('')}</div>
  </section>`;
}

export function renderGiveaway(giveaway, participation, geoSettings = [], stage = 'view', draft = {}, lang = 'ru') {
  if (!giveaway) return `<div class="view giveaway-view">${pageHead(tr(lang, 'title'), 'Partners Agent')}<section class="empty-state giveaway-empty">${icon('gift')}<h2>${tr(lang, 'none')}</h2><p>${tr(lang, 'noneText')}</p></section></div>`;
  const registrationOpen = giveaway.status === 'active' && new Date(giveaway.end_at) > new Date();
  if (stage === 'join') return `<div class="view giveaway-view">${pageHead(tr(lang, 'joinTitle'), giveaway.number)}${giveawayHero(giveaway, geoSettings, lang)}<form class="form-card giveaway-form" data-form="giveaway-join-data"><div class="form-kicker">${tr(lang, 'step')}</div><h2>${tr(lang, 'enter')}</h2><label class="field"><span>${tr(lang, 'geo')} *</span><select name="geo_code" required><option value="">${tr(lang, 'selectGeo')}</option>${giveaway.geo_codes.map(code => `<option value="${e(code)}" ${draft.geo_code === code ? 'selected' : ''}>${e(geoName(code, geoSettings))}</option>`).join('')}</select></label><label class="field"><span>${tr(lang, 'playerId')} *</span><input name="player_id" value="${e(draft.player_id)}" required maxlength="80" autocomplete="off" inputmode="numeric" placeholder="${e(tr(lang, 'playerPlaceholder'))}"></label><p class="form-help">${tr(lang, 'noExternalCheck')}</p><div class="flow-actions">${button(tr(lang, 'back'), 'type="button" data-giveaway-stage="view"', 'secondary')}${button(tr(lang, 'next'), 'type="submit"')}</div></form></div>`;
  if (stage === 'confirm') return `<div class="view giveaway-view">${pageHead(tr(lang, 'confirmTitle'), giveaway.number)}<section class="giveaway-confirm"><i>${icon('check')}</i><span>${tr(lang, 'ready')}</span><h2>${e(giveawayTitle(giveaway, lang))}</h2><dl><dt>🌍 ${tr(lang, 'geo')}</dt><dd>${e(geoName(draft.geo_code, geoSettings))}</dd><dt>🆔 ${tr(lang, 'playerId')}</dt><dd>${e(draft.player_id)}</dd></dl><p>${tr(lang, 'immutable')}</p>${button(tr(lang, 'confirm'), 'data-confirm-giveaway-join')}${button(tr(lang, 'changeId'), 'data-giveaway-stage="join"', 'secondary')}${button(tr(lang, 'cancel'), 'data-giveaway-stage="view"', 'secondary')}</section></div>`;
  const participationBlock = participation ? `<section class="giveaway-participation"><span>${tr(lang, 'already')}</span><h2>${e(participation.participant_number)}</h2><p>${e(geoName(participation.geo_code, geoSettings))} · ${tr(lang, 'playerId')}: ${e(participation.player_id)}</p>${button(tr(lang, 'mine'), 'data-giveaway-mine')}</section>` : registrationOpen ? button(tr(lang, 'join'), 'data-giveaway-stage="join"') : `<section class="giveaway-closed">${tr(lang, 'closed')}</section>`;
  return `<div class="view giveaway-view">${pageHead(tr(lang, 'title'), giveaway.number)}${giveawayHero(giveaway, geoSettings, lang)}${participationBlock}<section class="giveaway-tools">${button(`🏆 ${tr(lang, 'winners')}`, 'data-giveaway-winners', 'secondary')}${button(tr(lang, 'rules'), 'data-giveaway-rules', 'secondary')}${button(tr(lang, 'back'), 'data-nav="home"', 'secondary')}</section><details class="giveaway-rules" data-giveaway-rules-box><summary>${tr(lang, 'rules')}</summary><p>${e(giveaway.rules || tr(lang, 'rulesText'))}</p></details></div>`;
}

export function renderMyGiveaway(giveaway, participation, settings = [], lang = 'ru') {
  if (!giveaway || !participation) return `<div class="view giveaway-view">${pageHead(tr(lang, 'myParticipation'), tr(lang, 'title'))}<section class="empty-state">${icon('gift')}<h2>${tr(lang, 'noParticipation')}</h2><p>${tr(lang, 'noParticipationText')}</p>${button(tr(lang, 'toGiveaway'), 'data-nav="giveaway"')}</section></div>`;
  const status = { active: tr(lang, 'already'), winner: `🏆 ${tr(lang, 'winners')}`, excluded: tr(lang, 'excluded') }[participation.status] || tr(lang, 'drawn');
  return `<div class="view giveaway-view">${pageHead(tr(lang, 'myParticipation'), giveaway.number)}<section class="my-giveaway-card"><span>${status}</span><h1>${e(giveawayTitle(giveaway, lang))}</h1><dl><dt>${tr(lang, 'participantNumber')}</dt><dd>${e(participation.participant_number)}</dd><dt>${tr(lang, 'geo')}</dt><dd>${e(geoName(participation.geo_code, settings))}</dd><dt>${tr(lang, 'playerId')}</dt><dd>${e(participation.player_id)}</dd></dl></section>${button(tr(lang, 'toGiveaway'), 'data-nav="giveaway"', 'secondary')}</div>`;
}

export function renderGiveawayWinners(giveaway, lang = 'ru') {
  const winners = giveaway?.winners || [];
  return `<div class="view giveaway-view">${pageHead(`🏆 ${tr(lang, 'winners')}`, giveaway?.number || tr(lang, 'title'))}${winners.length ? `<section class="winner-stack">${winners.map((winner, index) => `<article><i>${index === 0 ? '🥇' : index === 1 ? '🥈' : index === 2 ? '🥉' : '🏆'}</i><div><span>${e(winner.participant.participant_number)}</span><b>${tr(lang, 'playerId')}: ${e(winner.participant.player_id)}</b><small>${tr(lang, 'geo')}: ${e(winner.participant.geo_code)}</small></div></article>`).join('')}</section>` : `<section class="empty-state">${icon('trophy')}<h2>${tr(lang, 'winnersNotSelected')}</h2><p>${tr(lang, 'winnersNotSelectedText')}</p></section>`}${button(tr(lang, 'back'), 'data-nav="giveaway"', 'secondary')}</div>`;
}

export function renderGiveawayManager(giveaways = [], geoSettings = [], lang = 'ru') {
  const list = giveaways.length ? giveaways.map(item => `<button class="giveaway-manager-row" data-giveaway-open="${item.id}"><i>${icon('gift')}</i><span><small>${e(item.number)} · ${e(statusLabel(item.status, lang))}</small><b>${e(giveawayTitle(item, lang))}</b><em>${item.participants_count} ${tr(lang, 'participants').replace('👥 ','')} · ${e(item.prize)}</em></span>${icon('arrow')}</button>`).join('') : `<section class="empty-state"><h2>${tr(lang, 'noneCreated')}</h2><p>${tr(lang, 'noneCreatedText')}</p></section>`;
  return `<div class="view giveaway-manager-view">${pageHead(tr(lang, 'management'), `${giveaways.length} ${tr(lang, 'total')}`)}${button(tr(lang, 'create'), 'data-nav="manager-giveaway-create"')}${list}</div>`;
}

export function renderGiveawayCreate(geoSettings = [], edit = null, lang = 'ru') {
  const g = edit || {}; const selected = new Set(g.geo_codes || []);
  const datetimeValue = value => { if (!value) return ''; const d = new Date(value); const p = n => String(n).padStart(2, '0'); return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`; };
  return `<div class="view giveaway-manager-view">${pageHead(edit ? tr(lang, 'edit') : tr(lang, 'create'), edit?.number || '—')}<form class="form-card giveaway-create-form" data-form="${edit ? 'giveaway-edit' : 'giveaway-create'}" ${edit ? `data-giveaway-id="${edit.id}"` : ''}><label class="field"><span>${tr(lang, 'name')}</span><input name="title" maxlength="180" value="${e(g.title)}" placeholder="${e(tr(lang, 'title'))}"></label><label class="field"><span>${tr(lang, 'description')}</span><textarea name="description">${e(g.description)}</textarea></label><label class="field"><span>${tr(lang, 'amount')} *</span><input name="prize" type="number" min="1" step="1" inputmode="numeric" required value="${e(g.prize)}" placeholder="500"></label><label class="field"><span>${tr(lang, 'winnerCount')} *</span><input name="winner_count" type="number" min="1" max="100" required value="${e(g.winner_count || 1)}"></label><label class="field"><span>${tr(lang, 'startAt')} *</span><input name="start_at" type="datetime-local" required value="${datetimeValue(g.start_at)}"></label><label class="field"><span>${tr(lang, 'endAt')} *</span><input name="end_at" type="datetime-local" required value="${datetimeValue(g.end_at)}"></label><fieldset class="giveaway-geo-select"><legend>${tr(lang, 'geoList')} *</legend>${geoSettings.map(item => `<label><input type="checkbox" name="geo_codes" value="${e(item.geo_code)}" ${selected.has(item.geo_code) ? 'checked' : ''}><span>${e(item.country)} · ${e(item.geo_code)}</span></label>`).join('')}</fieldset><label class="field"><span>${tr(lang, 'rules')}</span><textarea name="rules">${e(g.rules)}</textarea></label>${!edit ? `<label class="field"><span>${tr(lang, 'banner')}</span><input name="banner" type="file" accept="image/jpeg,image/png,image/webp"></label>` : ''}<div class="flow-actions">${button(tr(lang, 'cancel'), 'type="button" data-nav="manager-giveaways"', 'secondary')}${button(edit ? tr(lang, 'save') : tr(lang, 'preview'), 'type="submit"')}</div></form></div>`;
}

export function renderGiveawayManagerDetail(giveaway, participants = {}, history = [], geoSettings = [], lang = 'ru') {
  if (!giveaway) return `<div class="view">${pageHead(tr(lang, 'title'))}<section class="empty-state"><p>…</p></section></div>`;
  const lifecycle = giveaway.status === 'closed' ? button(tr(lang, 'draw'), `data-giveaway-draw="${giveaway.id}"`) : giveaway.status === 'draft' ? button(tr(lang, 'launch'), `data-giveaway-manager-action="launch" data-giveaway-id="${giveaway.id}"`) : giveaway.status === 'active' ? button(tr(lang, 'close'), `data-giveaway-manager-action="close" data-giveaway-id="${giveaway.id}"`, 'secondary') : '';
  const rows = (participants.participants || []).map(item => `<article><div><span>${e(item.participant_number)} · ${e(statusLabel(item.status, lang))}</span><b>${tr(lang, 'playerId')}: ${e(item.player_id)}</b><small>${tr(lang, 'geo')}: ${e(item.geo_code)} · ${localeDate(item.joined_at, lang)}</small></div>${item.status === 'excluded' ? `<button data-giveaway-restore="${item.id}">${tr(lang, 'restore')}</button>` : item.status === 'active' ? `<button class="danger" data-giveaway-exclude="${item.id}">${tr(lang, 'exclude')}</button>` : ''}</article>`).join('') || `<section class="empty-state"><h2>${tr(lang, 'noParticipants')}</h2></section>`;
  return `<div class="view giveaway-manager-view">${pageHead(tr(lang, 'management'), giveaway.number)}${giveawayHero(giveaway, geoSettings, lang)}<div class="giveaway-manager-actions">${lifecycle}${giveaway.status !== 'drawn' && giveaway.status !== 'cancelled' ? button(tr(lang, 'edit'), `data-giveaway-edit="${giveaway.id}"`, 'secondary') : ''}${['draft','active','closed'].includes(giveaway.status) ? button(tr(lang, 'cancelAction'), `data-giveaway-manager-action="cancel" data-giveaway-id="${giveaway.id}"`, 'secondary') : ''}</div><section class="giveaway-section"><div class="section-title"><span>${tr(lang, 'participants')}</span><h2>${participants.total || 0} ${tr(lang, 'total')}</h2></div><form class="giveaway-filter" data-form="giveaway-participants-filter" data-giveaway-id="${giveaway.id}"><input name="query" placeholder="${e(tr(lang, 'playerId'))}"><select name="status"><option value="">${tr(lang, 'allStatuses')}</option><option value="active">${tr(lang, 'active')}</option><option value="winner">${tr(lang, 'winners')}</option><option value="excluded">${tr(lang, 'excluded')}</option></select><select name="geo_code"><option value="">${tr(lang, 'allGeo')}</option>${giveaway.geo_codes.map(code => `<option value="${e(code)}">${e(geoName(code, geoSettings))}</option>`).join('')}</select>${button(tr(lang, 'search'), 'type="submit"', 'secondary')}</form><section class="manager-participant-list">${rows}</section></section><details class="manager-history"><summary>${tr(lang, 'history')} (${history.length})</summary><div>${history.map(item => `<p><b>${e(item.action)}</b><span>${localeDate(item.created_at, lang)}</span></p>`).join('') || '—'}</div></details>${button(tr(lang, 'back'), 'data-nav="manager-giveaways"', 'secondary')}</div>`;
}
