import { esc, icon, pageHead } from './ui.js?v=20260819-5';
const button=(text,attrs='',kind='primary')=>`<button class="app-btn ${kind}" ${attrs}>${text}</button>`;
const copy={
  ru:{heroTop:'Ваш центр',heroAccent:'партнёрского роста',heroText:'Заявки, материалы, проверки и поддержка — в одном рабочем пространстве.',openProfile:'Открыть кабинет',start:'Начать работу',viewStatus:'Посмотреть статус заявки',quick:'БЫСТРЫЙ ДОСТУП',panel:'Рабочая панель',services:'5 сервисов',registration:'РЕГИСТРАЦИЯ',become:'Стать агентом',sendApplication:'Отправить заявку',cabinet:'КАБИНЕТ',already:'Я уже агент',security:'БЕЗОПАСНОСТЬ',agentCheck:'Проверка агента',managerCheck:'Проверка менеджера',support:'Поддержка',managerHelp:'Помощь менеджера',agentInSystem:'Агент в системе',officialManager:'Официальный менеджер',agentHint:'Введите email или Telegram ID агента.',managerHint:'Введите username или Telegram ID менеджера.',agentPlaceholder:'Email или Telegram ID',managerPlaceholder:'@username или Telegram ID',checkButton:'Проверить',privacy:'Персональные данные других пользователей не отображаются.',applyTitle:'Стать агентом',applyStep:'Шаг 1 из 2 · ваши данные',name:'Имя',yourName:'Ваше имя',country:'Страна',yourCountry:'Ваша страна',phone:'Телефон',experience:'Опыт работы',consent:'Согласен с обработкой заявки.',submit:'Отправить заявку',checkSelf:'Проверить агента',selfSubtitle:'Статус по вашему Telegram ID',notFound:'Агент не найден',notFoundText:'Подайте заявку, чтобы начать работу.',stats:'Статистика',statsSubtitle:'Ваши реальные показатели',noStats:'Статистика пока недоступна',noPeriod:'Нет данных за период',statsLocked:'Доступ открывается после подтверждения агента.',statsEmpty:'Показатели появятся после первого периода работы.',supportSubtitle:'Поможем с заявкой и работой',online:'НА СВЯЗИ',needHelp:'Нужна помощь?',supportText:'Создайте обращение — менеджер ответит в Telegram.',createTicket:'Создать обращение',newTicket:'Новое обращение',answerTelegram:'Мы ответим в Telegram',subject:'Тема',category:'Категория',general:'Общий вопрос',application:'Заявка',tech:'Техническая проблема',message:'Сообщение',send:'Отправить',myAccount:'Мой кабинет',yourAccount:'Ваш аккаунт',user:'Пользователь',instructions:'Инструкции',applicationLabel:'ЗАЯВКА'},
  en:{heroTop:'Your hub for',heroAccent:'partner growth',heroText:'Applications, verification and support in one workspace.',openProfile:'Open account',start:'Get started',viewStatus:'View application status',quick:'QUICK ACCESS',panel:'Workspace',services:'5 services',registration:'REGISTRATION',become:'Become an agent',sendApplication:'Submit an application',cabinet:'ACCOUNT',already:'I am already an agent',security:'SECURITY',agentCheck:'Verify agent',managerCheck:'Verify manager',support:'Support',managerHelp:'Contact support',agentInSystem:'Agent verification',officialManager:'Official manager',agentHint:'Enter the agent email or Telegram ID.',managerHint:'Enter the manager username or Telegram ID.',agentPlaceholder:'Email or Telegram ID',managerPlaceholder:'@username or Telegram ID',checkButton:'Verify',privacy:'Other users’ personal data is never displayed.',applyTitle:'Become an agent',applyStep:'Step 1 of 2 · your details',name:'Name',yourName:'Your name',country:'Country',yourCountry:'Your country',phone:'Phone',experience:'Work experience',consent:'I agree to the processing of my application.',submit:'Submit application',checkSelf:'Check agent status',selfSubtitle:'Status linked to your Telegram ID',notFound:'Agent not found',notFoundText:'Submit an application to get started.',stats:'Statistics',statsSubtitle:'Your actual performance',noStats:'Statistics are not available yet',noPeriod:'No data for this period',statsLocked:'Access opens after agent approval.',statsEmpty:'Performance will appear after your first working period.',supportSubtitle:'Help with your application and work',online:'ONLINE',needHelp:'Need help?',supportText:'Create a ticket and a manager will reply in Telegram.',createTicket:'Create ticket',newTicket:'New support ticket',answerTelegram:'We will reply in Telegram',subject:'Subject',category:'Category',general:'General question',application:'Application',tech:'Technical issue',message:'Message',send:'Send',myAccount:'My account',yourAccount:'Your profile',user:'User',instructions:'Instructions',applicationLabel:'APPLICATION'}
};
const text=lang=>copy[lang]||copy.ru;
const statuses=lang=>lang==='en'?{reviewing:['⏳','Application under review','We are checking your details.'],approved:['✅','Agent approved','Your account is active.'],blocked:['❌','Access restricted','Please contact support.'],rejected:['⚠️','More information needed','A manager will contact you.']}:{reviewing:['⏳','Заявка на рассмотрении','Мы проверяем данные.'],approved:['✅','Агент подтверждён','Ваш кабинет активен.'],blocked:['❌','Доступ ограничен','Обратитесь в поддержку.'],rejected:['⚠️','Нужны дополнительные данные','Менеджер свяжется с вами.']};
export const loading=()=>'<div class="view skeleton"><i></i><i></i><i></i></div>';
export function home(account,lang='ru'){
  const c=text(lang),info=statuses(lang);
  const a=account?.application;
  const status=a?(info[a.status]||info.reviewing):null;
  return `<div class="view melbet-dashboard">
    <section class="kinetic-hero">
      <div class="hero-orbit" aria-hidden="true"></div>
      <div class="hero-brand"><b>MEL</b><strong>BET</strong><span>PARTNERS</span></div>
      <div class="hero-badge">AGENT & AFFILIATE NETWORK</div>
      <h1>${c.heroTop}<br><em>${c.heroAccent}</em></h1>
      <p>${c.heroText}</p>
      <button class="hero-action" data-nav="${a?'profile':'apply'}"><span>${a?c.openProfile:c.start}</span>${icon('arrow')}</button>
    </section>
    ${status?`<button class="application-status compact-status" data-nav="check"><span>${status[0]}</span><div><b>${status[1]}</b><small>${c.viewStatus}</small></div>${icon('arrow')}</button>`:''}
    <div class="dashboard-heading"><div><span>${c.quick}</span><h2>${c.panel}</h2></div><small>${c.services}</small></div>
    <section class="action-deck">
      <button class="deck-card deck-agent" data-nav="apply"><i>${icon('briefcase')}</i><span><small>${c.registration}</small><b>${c.become}</b><em>${c.sendApplication}</em></span>${icon('arrow')}</button>
      <button class="deck-card deck-partner" data-nav="check"><i>${icon('user')}</i><span><small>${c.cabinet}</small><b>${c.already}</b></span>${icon('arrow')}</button>
      <button class="deck-card deck-media" data-nav="agent_lookup"><i>${icon('search')}</i><span><small>${c.security}</small><b>${c.agentCheck}</b></span>${icon('arrow')}</button>
      <button class="deck-card deck-contact" data-nav="manager_lookup"><i>${icon('shield')}</i><span><b>${c.managerCheck}</b></span></button>
      <button class="deck-card deck-blocked" data-nav="support"><i>${icon('message')}</i><span><b>${c.support}</b><em>${c.managerHelp}</em></span></button>
    </section>
  </div>`
}
export function agents(account,lang='ru'){const info=statuses(lang),a=account?.application;return `<div class="view">${pageHead('Агенты','MELBET Partners')}${a?`<section class="status-card"><b>${(info[a.status]||info.reviewing)[0]}</b><h2>${(info[a.status]||info.reviewing)[1]}</h2><p>${(info[a.status]||info.reviewing)[2]}</p>${button('Открыть кабинет','data-nav="profile"')}</section>`:`<section class="choice-stack"><button class="featured" data-nav="apply">${icon('briefcase')}<span><b>Стать агентом</b><small>Подать заявку на регистрацию</small></span>${icon('arrow')}</button><button data-nav="check">${icon('user')}<span><b>Я уже агент</b><small>Проверить статус по Telegram ID</small></span>${icon('arrow')}</button></section>`}</div>`}
export const partners=()=>`<div class="view">${pageHead('Партнёры','MELBET Partners')}<section class="choice-stack"><button class="featured" data-nav="support">${icon('users')}<span><b>Стать партнёром</b><small>Связаться с менеджером программы</small></span>${icon('arrow')}</button><button data-nav="profile">${icon('user')}<span><b>Я уже партнёр</b><small>Открыть личный кабинет</small></span>${icon('arrow')}</button></section></div>`;
export const banners=()=>`<div class="view">${pageHead('Получить баннер','Материалы для продвижения')}<div class="category-tabs"><button class="active">Все</button><button>Telegram</button><button>Stories</button><button>Posts</button></div><section class="banner-empty">${icon('image')}<h2>Материалы готовятся</h2><p>Опубликованные администратором баннеры появятся здесь без обновления приложения.</p></section></div>`;
export function lookup(kind='agent',lang='ru'){
  const c=text(lang);
  const manager=kind==='manager';
  return `<div class="view">${pageHead(manager?c.managerCheck:c.agentCheck,manager?c.managerPlaceholder:c.agentPlaceholder)}<section class="lookup-premium"><div class="lookup-icon">${icon(manager?'shield':'search')}</div><h2>${manager?c.officialManager:c.agentInSystem}</h2><p>${manager?c.managerHint:c.agentHint}</p><form data-form="lookup" data-check="${kind}"><input name="query" required placeholder="${manager?c.managerPlaceholder:c.agentPlaceholder}">${button(`${icon('search')} ${c.checkButton}`,'type="submit"')}</form><div class="lookup-result" hidden></div><div class="lookup-note">${c.privacy}</div></section></div>`
}
export const faq=()=>{const questions=['Какие виды трафика разрешены?','Какие модели сотрудничества доступны?','Есть ли реферальная программа?','Как часто обновляется статистика?','Когда происходят выплаты?','Как стать агентом?','Как получить рекламные материалы?','Как связаться с менеджером?'];return `<div class="view">${pageHead('Вопросы и ответы','Для партнёров и агентов')}<div class="faq-switch"><button class="active">Для партнёров</button><button>Для агентов</button></div><section class="faq-stack">${questions.map(q=>`<article class="faq-row"><button class="faq-question">${q}<i>+</i></button><p>Подробный ответ будет добавлен администратором программы.</p></article>`).join('')}</section></div>`}
export function application(v={},lang='ru'){const c=text(lang),val=n=>esc(v[n]||'');return `<div class="view">${pageHead(c.applyTitle,c.applyStep)}<form class="form-card" data-form="application"><div class="stepper"><i class="active"></i><i></i></div>${[[c.name,'name',c.yourName],['Email','email','name@example.com'],[c.country,'country',c.yourCountry],[c.phone,'phone','+7 000 000 00 00']].map(([l,n,p])=>`<label class="field"><span>${l} *</span><input ${n==='email'?'type="email"':''} name="${n}" required value="${val(n)}" placeholder="${p}"></label>`).join('')}<label class="field"><span>${c.experience}</span><textarea name="experience">${val('experience')}</textarea></label><label class="consent"><input type="checkbox" required><span>${c.consent}</span></label>${button(c.submit,'type="submit"')}</form></div>`}
export function check(account,lang='ru'){const c=text(lang),info=statuses(lang),a=account?.application,s=a?(info[a.status]||info.reviewing):['❌',c.notFound,c.notFoundText];return `<div class="view">${pageHead(c.checkSelf,c.selfSubtitle)}<section class="status-card"><b>${s[0]}</b><h2>${s[1]}</h2><p>${s[2]}</p>${a?`<small>${c.applicationLabel} №${a.id}</small>`:button(c.become,'data-nav="apply"')}</section></div>`}
export function stats(account,lang='ru'){const c=text(lang),active=account?.application?.status==='approved';return `<div class="view">${pageHead(c.stats,c.statsSubtitle)}<section class="empty-state">${icon('chart')}<h2>${active?c.noPeriod:c.noStats}</h2><p>${active?c.statsEmpty:c.statsLocked}</p></section></div>`}
export const instructions=()=>`<div class="view">${pageHead('Инструкции','Всё важное — коротко')}<section class="instruction-list">${[['1','Как начать работу','Заполните заявку и дождитесь подтверждения.'],['2','Работа с игроками','Используйте только согласованные материалы.'],['3','Важные правила','Не передавайте доступ третьим лицам.']].map(x=>`<article><b>${x[0]}</b><div><h2>${x[1]}</h2><p>${x[2]}</p></div></article>`).join('')}</section></div>`;
export const support=(lang='ru')=>{const c=text(lang);return `<div class="view">${pageHead(c.support,c.supportSubtitle)}<section class="soft-hero compact"><span>${c.online}</span><h1>${c.needHelp}</h1><p>${c.supportText}</p>${button(c.createTicket,'data-nav="ticket"')}</section></div>`};
export const ticket=(lang='ru')=>{const c=text(lang);return `<div class="view">${pageHead(c.newTicket,c.answerTelegram)}<form class="form-card" data-form="ticket"><label class="field"><span>${c.subject} *</span><input name="subject" required></label><label class="field"><span>${c.category} *</span><select name="category"><option>${c.general}</option><option>${c.application}</option><option>${c.tech}</option></select></label><label class="field"><span>${c.message} *</span><textarea name="body" required></textarea></label>${button(c.send,'type="submit"')}</form></div>`};
export const profile=(account,lang='ru')=>{const c=text(lang),u=account?.telegram||{},a=account?.application;return `<div class="view">${pageHead(c.myAccount,c.yourAccount)}<section class="profile-hero"><div class="profile-avatar">${esc((u.first_name||'P')[0])}</div><div><h2>${esc(u.first_name||c.user)}</h2><p>${u.username?'@'+esc(u.username):'Telegram'}</p><span class="status-tag">${a?.status||'GUEST'}</span></div></section><section class="id-card"><span>TELEGRAM ID</span><b>${u.id||'—'}</b></section>${a?`<section class="id-card"><span>${c.applicationLabel}</span><b>№${a.id}</b></section>`:''}${button(c.instructions,'data-nav="instructions"','secondary')}${button(c.support,'data-nav="support"','secondary')}</div>`};
